name: Publish Git Urls to npmjs.org

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup node environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ">=14"
          registry-url: https://registry.npmjs.org/

      - name: Checkout code 
        uses: actions/checkout@v2
      
      - name: Install
        run: |
          npm install
        working-directory: ./packages/git-urls

      - name: Build
        run: npm run build
        working-directory: ./packages/git-urls

      - name: Lint
        run: npm run lint
        working-directory: ./packages/git-urls

      - name: Test
        run: npm run test
        working-directory: ./packages/git-urls
      
      - name: Publish
        run: npm publish --access public
        working-directory: ./packages/git-urls
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
