name: Publish VS Code Extension to marketplace

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ">=14"
          registry-url: https://registry.npmjs.org/

      - name: Checkout code 
        uses: actions/checkout@v2
      
      - name: Install
        run: |
          npx lerna bootstrap
          npm install -g vsce

      - name: Build
        run: npx lerna run build
      
      - name: Publish
        environment: production
        run: vsce publish -p ${{secrets.TOKEN}}
        working-directory: ./packages/vscode-gitlink
